### ISSUE TITLE
add support for longetuginal data

### ISSUE THREAD

**Issue by philloooo** [occ-data/bpadictionary#17]
Bob: standard timestamp?..

**Comment by dmiller15** [comment]
Longitudinal data describes data taken from the same subjects over an extended period of time. Since it is related to the subjects, this longitudinal data would be applicable to children nodes of the case node:
- Demographic
- Family History
- Exposure
- Diagnosis
- Clinical Test
- Treatment
- Sample

We currently have a planned solution to importing longitudinal data with the inclusion of MMRF in the GDC. For similarity's sake we'll likely implement the same solution here with one change. In NCI projects, the age of the patients is obfuscated by indexing the dates of followups on the date of initial pathological diagnosis. Members of the BloodPAC have expressed interest in simply using a datetime stamp. We could use this in lieu of the days_to values we have.
